// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleAdmin.DataAccess.Models
{
    public partial class Item
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public bool IsEnabled { get; set; }
        public string Photo { get; set; }
        public string Url { get; set; }
        public string Seodescription { get; set; }
        public string Seotitle { get; set; }
        public string Seokeywords { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public int LastModifiedBy { get; set; }

        public virtual Category Category { get; set; }
        public virtual User CreatedByNavigation { get; set; }
        public virtual User LastModifiedByNavigation { get; set; }
    }
}