// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleAdmin.DataAccess.Models
{
    public partial class User
    {
        public User()
        {
            CategoryCreatedByNavigation = new HashSet<Category>();
            CategoryLastModifiedByNavigation = new HashSet<Category>();
            InverseCreatedByNavigation = new HashSet<User>();
            InverseLastModifiedByNavigation = new HashSet<User>();
            ItemCreatedByNavigation = new HashSet<Item>();
            ItemLastModifiedByNavigation = new HashSet<Item>();
        }

        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public bool IsEnabled { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public int? LastModifiedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User LastModifiedByNavigation { get; set; }
        public virtual ICollection<Category> CategoryCreatedByNavigation { get; set; }
        public virtual ICollection<Category> CategoryLastModifiedByNavigation { get; set; }
        public virtual ICollection<User> InverseCreatedByNavigation { get; set; }
        public virtual ICollection<User> InverseLastModifiedByNavigation { get; set; }
        public virtual ICollection<Item> ItemCreatedByNavigation { get; set; }
        public virtual ICollection<Item> ItemLastModifiedByNavigation { get; set; }
    }
}